name: DownloadVS2022
on:
  push:
    branches:
      - master  # 当推送到 master 分支时触发
  workflow_dispatch:  # 允许手动触发

jobs:
  download_vs:
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Download Visual Studio 2022 Enterprise
        run: |
          # 创建下载目录
          mkdir D:\Admin\vs2022VC
          
          # 下载Visual Studio 2022企业版安装程序
          Invoke-WebRequest -Uri "https://aka.ms/vs/17/release/VisualStudioSetup.exe" -OutFile "D:\Admin\vs2022VC\VisualStudioSetup.exe"

      - name: Execute Visual Studio layout command
        run: |
          # 进入下载目录
          cd D:\Admin\vs2022VC
          # 执行布局命令，确保引用根目录的 .vsconfig 文件
          Start-Process -Wait -FilePath "D:\Admin\vs2022VC\VisualStudioSetup.exe" -ArgumentList "--layout D:\Admin\vs2022VC\VSLayout --config `"$GITHUB_WORKSPACE\.vsconfig`""

      - name: Pack the downloaded content
        run: |
          # 使用7-Zip打包为tar.zst格式
          & 'C:\Program Files\7-Zip\7z.exe' a -tZST "D:\Admin\vs2022VC\VSLayout.tar.zst" "D:\Admin\vs2022VC\VSLayout\*"

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: VS2022-Layout-Artifact  # 提供上传文件的名称
          path: D:\Admin\vs2022VC\VSLayout.tar.zst  # 指定需要上传的tar.zst文件路径

      - name: Clean up
        run: |
          # 删除临时下载文件
          Remove-Item -Recurse -Force D:\Admin\vs2022VC
