name: DownloadVS2022
on:
  push:
    branches:
      - master  # 当推送到 master 分支时触发
  workflow_dispatch:  # 允许手动触发

jobs:
  download_vs:
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Download Visual Studio 2022 Enterprise
        run: |
          # 下载 Visual Studio 2022 企业版安装程序
          curl -L -o "C:\VisualStudioSetup.exe" "https://aka.ms/vs/17/release/vs_enterprise.exe"
          # 检查文件是否下载成功
          if not exist "C:\VisualStudioSetup.exe" (
              echo VisualStudioSetup.exe 下载失败，文件未找到！
              exit /b 1
          )
          # 输出文件大小
          for %%I in ("C:\VisualStudioSetup.exe") do echo 文件已下载：%%~nxI，大小：%%~zI 字节

      - name: Execute Visual Studio layout command
        run: |
          # 使用 CMD 命令执行布局命令
          "C:\VisualStudioSetup.exe" --layout "C:\VSLayout" --config "%GITHUB_WORKSPACE%\.vsconfig"

      - name: Pack the downloaded content
        run: |
          # 先确保 7-Zip 可用，然后打包为 tar.zst 格式
          "C:\Program Files\7-Zip\7z.exe" a -tZST "C:\VSLayout.tar.zst" "C:\VSLayout\*"

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: VS2022-Layout-Artifact  # 提供上传文件的名称
          path: C:\VSLayout.tar.zst  # 指定需要上传的 tar.zst 文件路径

      - name: Clean up
        run: |
          # 删除临时下载文件
          del /q C:\VisualStudioSetup.exe
          rmdir /s /q C:\VSLayout
