name: DownloadVS2022
on:
  push:
    branches:
      - main  # 替换为你的主分支名称
  workflow_dispatch:

jobs:
  download_vs:
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Download Visual Studio 2022 Enterprise
        run: |
          mkdir D:\Admin\vs2022VC
          Invoke-WebRequest -Uri "https://aka.ms/vs/17/release/VisualStudioSetup.exe" -OutFile "D:\Admin\vs2022VC\VisualStudioSetup.exe"

      - name: Execute Visual Studio layout command
        run: |
          cd D:\Admin\vs2022VC
          Start-Process -Wait -FilePath "VisualStudioSetup.exe" -ArgumentList '--layout D:\Admin\vs2022VC\VSLayout --config "D:\Admin\vs2022VC\.vsconfig"'

      - name: Pack the downloaded content
        run: |
          & 'C:\Program Files\7-Zip\7z.exe' a -tZST "D:\Admin\vs2022VC\VSLayout.tar.zst" "D:\Admin\vs2022VC\VSLayout\*"

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: VS2022-Layout-Artifact
          path: D:\Admin\vs2022VC\VSLayout.tar.zst

      - name: Clean up
        run: |
          Remove-Item -Recurse -Force D:\Admin\vs2022VC
