name: DownloadVS2022
on:
  push:
    branches:
      - master  # 当推送到 master 分支时触发
  workflow_dispatch:  # 允许手动触发

jobs:
  download_vs:
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Create layout directory
        run: |
          # 创建布局目录
          md C:\VSLayout

      - name: Execute Visual Studio layout command
        run: |
          # 使用 CMD 命令执行布局命令，假设 VisualStudioSetup.exe 在根目录
          "C:\github\<your-repo-name>\VisualStudioSetup.exe" --layout "C:\VSLayout" --config "%GITHUB_WORKSPACE%\.vsconfig"

      - name: Pack the downloaded content
        run: |
          # 先确保 7-Zip 可用，然后打包为 tar.zst 格式
          "C:\Program Files\7-Zip\7z.exe" a -tZST "C:\VSLayout.tar.zst" "C:\VSLayout\*"

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: VS2022-Layout-Artifact  # 提供上传文件的名称
          path: C:\VSLayout.tar.zst  # 指定需要上传的 tar.zst 文件路径

      - name: Clean up
        run: |
          # 删除临时布局目录
          rmdir /s /q C:\VSLayout
