name: DownloadVS2022
on:
  push:
    branches:
      - master
  workflow_dispatch:  # 允许手动触发

jobs:
  download_vs:
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Execute Visual Studio layout command
        run: |
          cmd /c "VisualStudioSetup.exe --passive  --layout VSLayout --config .vsconfig"

      - name: Pack the downloaded content
        run: |
          cmd /c "7z a VSLayout.7z VSLayout\*"

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: VS2022-Layout-Artifact
          path: VSLayout.tar.zst