name: ci
on:
  push:
    branches:
      - master
  workflow_dispatch:  # 允许手动触发

jobs:
  download_vs:
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: offline Visual Studio 2022 layout
        run: |
          cmd /c "VisualStudioSetup.exe --passive  --lang zh-CN --layout VSLayout --fix --useLatestInstaller --config .vsconfig "

      - name: Pack layout
        run: |
          cmd /c "7z a VSLayout.7z VSLayout\*"

      - name: Upload packed layout
        uses: actions/upload-artifact@v4
        with:
          name: VS2022-Layout-Artifact
          path: VSLayout.7z