name: DownloadVS2022
on:
  push:
    branches:
      - master  # 当推送到 master 分支时触发
  workflow_dispatch:  # 允许手动触发

jobs:
  download_vs:
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Create download directory
        run: |
          # 在C盘创建下载目录（如果已存在不会抛出错误）
          New-Item -ItemType Directory -Path C:\Admin\vs2022VC -Force

      - name: Download Visual Studio 2022 Enterprise
        run: |
          # 下载Visual Studio 2022企业版安装程序
          Invoke-WebRequest -Uri "https://aka.ms/vs/17/release/VisualStudioSetup.exe" -OutFile "C:\Admin\vs2022VC\VisualStudioSetup.exe"
          
          # 检查文件是否下载成功并有效
          if (-Not (Test-Path "C:\Admin\vs2022VC\VisualStudioSetup.exe")) {
            Write-Error "VisualStudioSetup.exe 下载失败，文件未找到！"
            exit 1
          }
          # 输出文件信息，检查文件大小等
          $fileInfo = Get-Item "C:\Admin\vs2022VC\VisualStudioSetup.exe"
          Write-Host "文件已下载：$($fileInfo.FullName)，大小：$($fileInfo.Length) 字节"

          # 如果文件大小小于 100 字节则视为无效文件
          if ($fileInfo.Length -lt 100) {
            Write-Error "下载的文件可能无效，文件大小为：$($fileInfo.Length) 字节"
            exit 1
          }

      - name: Execute Visual Studio layout command
        run: |
          # 验证文件是否为可执行文件，然后尝试执行
          Start-Process -Wait -FilePath "C:\Admin\vs2022VC\VisualStudioSetup.exe" -ArgumentList "--layout C:\Admin\vs2022VC\VSLayout --config `"$GITHUB_WORKSPACE\.vsconfig`""

      - name: Pack the downloaded content
        run: |
          # 使用7-Zip打包为tar.zst格式
          & 'C:\Program Files\7-Zip\7z.exe' a -tZST "C:\Admin\vs2022VC\VSLayout.tar.zst" "C:\Admin\vs2022VC\VSLayout\*"

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: VS2022-Layout-Artifact  # 提供上传文件的名称
          path: C:\Admin\vs2022VC\VSLayout.tar.zst  # 指定需要上传的tar.zst文件路径

      - name: Clean up
        run: |
          # 删除临时下载文件
          Remove-Item -Recurse -Force C:\Admin\vs2022VC
